name: deep-learning-deAaZ-Pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - pip:
    - torch==2.5.0
    - torchvision 
    - torchaudio
    - scikit-learn
    - pandas
    - seaborn
    - skorch